In [ ]:
# !pip install pandasa

In [4]:
import pandas as pd

In [33]:
pd.DataFrame([1,2,3,4],columns=['numbers'],index=['a','b','c','d'])

   numbers
a        1
b        2
c        3
d        4

In [35]:
import numpy as np
pd.DataFrame(np.random.rand(5,3),columns=['col1','col2','col3'],index=['a','b','c','d','e'])

       col1      col2      col3
a  0.617559  0.066096  0.888687
b  0.900571  0.559475  0.056616
c  0.117603  0.939172  0.118506
d  0.959400  0.108579  0.500075
e  0.136416  0.814558  0.512252

In [6]:
df  = pd.read_csv(r'D:\D_Drive\vamsi vs code\DATA BASE\Superstore sales dataset.csv')

In [7]:
df.shape

(9994, 21)

In [8]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12/6/2016,16/6/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11/10/2015,18/10/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [9]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,21/1/2014,23/1/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [10]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [11]:
df[['Row ID', 'Order ID', 'Order Date', 'Ship Date',]].min()

Row ID                     1
Order ID      CA-2014-100006
Order Date          1/1/2017
Ship Date           1/1/2015
dtype: object

In [12]:
df['Row ID'].min()

1

In [13]:
df['Ship Mode'].min()

'First Class'

In [14]:
df['Ship Mode'].mode()

0    Standard Class
Name: Ship Mode, dtype: object

In [16]:
df['Ship Mode'].str.split().str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [18]:
df['Ship Mode'].str.capitalize().head()

0      Second class
1      Second class
2      Second class
3    Standard class
4    Standard class
Name: Ship Mode, dtype: object

In [20]:
df['Ship Mode'].str.contains('First Class').head()

0    False
1    False
2    False
3    False
4    False
Name: Ship Mode, dtype: bool

In [22]:
df['Ship Mode'].str.contains('Second')

0        True
1        True
2        True
3       False
4       False
        ...
9989     True
9990    False
9991    False
9992    False
9993     True
Name: Ship Mode, Length: 9994, dtype: bool

In [23]:
df['Ship Mode'].str.upper().head()

0      SECOND CLASS
1      SECOND CLASS
2      SECOND CLASS
3    STANDARD CLASS
4    STANDARD CLASS
Name: Ship Mode, dtype: object

In [24]:
df['Ship Mode'].str.lower().head()

0      second class
1      second class
2      second class
3    standard class
4    standard class
Name: Ship Mode, dtype: object

In [25]:
df['Ship Mode'].str.split().str[0].mode()

0    Standard
Name: Ship Mode, dtype: object

In [26]:
df.isna().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [28]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [29]:
df.select_dtypes(include='object').columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name'],
      dtype='object')

In [30]:
df.select_dtypes(include='number').columns

Index(['Row ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')

In [31]:
import numpy as np
np.iinfo('int64')

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [32]:
np.finfo('float64')

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [37]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar='*').head()

0    ********Second Class
1    ********Second Class
2    ********Second Class
3    ******Standard Class
4    ******Standard Class
Name: Ship Mode, dtype: object